version: 2.1

cache_key: &cache_key cg-front-end-deps-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  # The test job
  npm-install:
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: npm-install
          command: npm ci
          - save_cache:
              key: *cache_key
              paths:
                - node_modules
